install
KVM_TEST_MEDIUM
text
reboot
lang en_US.UTF-8
keyboard us
key 2515dd4e215225dd
network --bootproto dhcp
rootpw redhat
firewall --enabled --ssh
selinux --enforcing
timezone --utc Asia/Shanghai
firstboot --disable
bootloader --location=mbr --append="console=tty0 console=ttyS0,115200"
zerombr
clearpart --all --initlabel
autopart
xconfig --startxonboot
poweroff

%packages
@admin-tools
@afrikaans-support
@arabic-support
@assamese-support
@authoring-and-publishing
@base
@base-x
@bengali-support
@brazilian-support
@breton-support
@british-support
@bulgarian-support
@catalan-support
@chinese-support
@core
@croatian-support
@czech-support
@danish-support
@development-libs
@development-tools
@dialup
@dns-server
@dutch-support
@editors
@engineering-and-scientific
@estonian-support
@faeroese-support
@finnish-support
@french-support
@ftp-server
@gaelic-support
@galician-support
@games
@german-support
@gnome-desktop
@gnome-software-development
@graphical-internet
@graphics
@greek-support
@gujarati-support
@hebrew-support
@hindi-support
@hungarian-support
@hyperv
@icelandic-support
@indonesian-support
@irish-support
@italian-support
@japanese-support
@java
@java-development
@kannada-support
@kde-desktop
@kde-software-development
@korean-support
@kvm
@legacy-network-server
@legacy-software-development
@legacy-software-support
@mail-server
@malayalam-support
@marathi-support
@mysql
@network-server
@news-server
@norwegian-support
@office
@openfabrics-enterprise-distribution
@oriya-support
@polish-support
@portuguese-support
@printing
@punjabi-support
@romanian-support
@ruby
@russian-support
@serbian-support
@server-cfg
@sinhala-support
@slovak-support
@slovenian-support
@smb-server
@sound-and-video
@spanish-support
@sql-server
@swedish-support
@system-tools
@tamil-support
@telugu-support
@text-internet
@thai-support
@turkish-support
@ukrainian-support
@urdu-support
@web-server
@welsh-support
@xen
@x-software-development
adjtimex
agg
aide
amanda-client
amanda-server
am-utils
arptables_jf
arpwatch
audit
authd
avahi-tools
blktrace
bluez-utils-cups
bogl
bogl-bterm
bootparamd
bridge-utils
brltty
bsh-demo
cmake
compat-dapl-static
compat-db
compat-openldap
compat-readline43
compat-slang
convmv
cpufreq-utils
createrepo
cvs-inetd
cyrus-imapd
cyrus-imapd-perl
dapl-static
dejagnu
device-mapper-multipath
dhcp
dhcpv6
dmraid-events-logwatch
dnsmasq
dstat
dtach
dvgrab
e4fsprogs
edac-utils
efax
ElectricFence
emacs
emacs-nox
epic
eruby
exim
exim-doc
expect
fcoe-utils
festival
fipscheck
fipscheck-devel
freeipmi
freeradius
fuse
fuse-devel
fuse-libs
gcc44
gcc44-c++
gcc44-gfortran
gcc-gnat
gcc-objc
gftp
gimp
gimp-data-extras
gimp-help
gnome-nettool
gnupg2
gnuplot-emacs
gnutls-utils
gob2
gpart
gsl
gtk+
hardlink
hesinfo
hfsutils
hplip3
hwbrowser
ibsim
icon-naming-utils
icon-slicer
imake
iotop
iptraf
iscsi-initiator-utils
java-1.6.0-openjdk
java-1.6.0-openjdk-devel
java-1.7.0-openjdk
java-1.7.0-openjdk-devel
kdesdk-devel
kdewebdev
kexec-tools
keyutils
krb5-server
ktune
lam
lapack
libassuan-devel
libdbi-dbd-pgsql
libgconf-java
libgfortran44
libglade-java
libgnome-java
libgtk-java
libhbaapi
libhbaapi-devel
libhbalinux
libksba
libksba-devel
libpciaccess
libpciaccess-devel
libsane-hpaio
libstdc++44-devel
libXp-devel
log4cpp-devel
lslk
lsscsi
lynx
mailman
mc
memtest86+
mesa-libGLU-devel
mesa-libGLw-devel
mikmod
mod_auth_kerb
mod_auth_mysql
mod_auth_pgsql
mod_authz_ldap
mod_nss
mod_revocator
mpitests-mvapich
mpitests-mvapich2
mrtg
mstflint
mt-st
mtx
mvapich
mvapich2
mysql-bench
mysql-connector-odbc64
mysql-devel
nasm
nedit
net-snmp-utils
nfs4-acl-tools
nmap-frontend
openCryptoki
OpenIPMI-gui
openldap-servers
openldap-servers-overlays
openmotif22
openmotif-devel
openscap
opensm
openssl097a
openswan
perl-Archive-Zip
perl-Convert-ASN1
perl-Crypt-SSLeay
perl-DateManip
perl-LDAP
perl-libxml-perl
perl-Mozilla-LDAP
perl-TimeDate
perl-XML-Dumper
perl-XML-Grove
perl-XML-NamespaceSupport
perl-XML-SAX
perl-XML-Twig
pexpect
php-mysql
php-odbc
php-pear
php-pgsql
pinentry
postfix
postgresql-contrib
postgresql-docs
postgresql-jdbc
postgresql-odbc
postgresql-odbc64
postgresql-pl
postgresql-tcl
postgresql-test
privoxy
pth
pth-devel
pvm
python-dmidecode
python-docs
python-imaging
python-suds
qlvnictools
qt4
qt-MySQL
qt-ODBC
quagga
radvd
rarpd
rdesktop
rsh-server
ruby-ri
rusers-server
sblim-cmpi-dhcp-devel
sblim-gather
sblim-wbemcli
sgpio
squashfs-tools
squirrelmail
srptools
sssd
star
statserial
subscription-manager-migration
subscription-manager-migration-data
sysstat
system-config-bind
system-config-boot
system-config-kickstart
system-switch-mail-gnome
systemtap-sdt-devel
talk-server
telnet-server
tetex-xdvi
tftp
tftp-server
tn5250
tog-pegasus
tog-pegasus-devel
tomcat5
tomcat5-admin-webapps
tomcat5-webapps
tpm-tools
trousers
tsclient
tunctl
unifdef
unixODBC-kde
uucp
uuidd
vim-X11
vlock
vnc-server
wacomexpresskeys
watchdog
wireshark-gnome
x3270
x86info
xcdroast
xchat
xferstats
xfig
xorg-x11-server-sdk
xorg-x11-server-Xnest
xorg-x11-server-Xvfb
xorg-x11-utils
xorg-x11-xbitmaps
ypserv
yum-utils

%post --interpreter /usr/bin/python
import socket, os
os.system('dhclient')
os.system('chkconfig sshd on')
os.system('iptables -F')
os.system('echo 0 > /selinux/enforce')
os.system('mv /etc/yum.repos.d/ /etc/yum.repos.d.bk')
os.system('mkdir /etc/yum.repos.d')
os.system('cp -r /etc/yum.repos.d.bk/redhat.repo /etc/yum.repos.d')
os.system('sed -i "s/default=0/default=1/" /boot/grub/grub.conf')
os.system('sed -i "/^HWADDR/d" /etc/sysconfig/network-scripts/ifcfg-eth0')
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(("autotest_host_ip", 12323))
client.send("done")
client.close()
